[package]
name = "plex-letterboxd-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
regex = "1.11.2"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
secrecy = "0.10.3"
select = "0.6.1"
serde = "1.0.225"
url = "2.5.7"
